
services:
  caddy:
    container_name: immich_caddy
    image: caddy:2-alpine@sha256:77c07d5ebfa5be9fd6c820d2094ae662c9e7eeb9bf98346b7f639900263ee2a2
    depends_on:
      - immich-server
    ports:
      - 443:443
      - 80:80
    volumes:
      - ${CADDY_LOCATION:-./caddy}/Caddyfile:/etc/caddy/Caddyfile
      - ${CADDY_LOCATION:-./caddy}/caddy_conf:/config
      - ${CADDY_LOCATION:-./caddy}/caddy_data:/data
    restart: always
