
services:
  caddy:
    container_name: immich_caddy
    image: caddy:2-alpine@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648
    depends_on:
      - immich-server
    ports:
      - 443:443
      - 80:80
    volumes:
      - ${CADDY_LOCATION:-./caddy}/Caddyfile:/etc/caddy/Caddyfile
      - ${CADDY_LOCATION:-./caddy}/caddy_conf:/config
      - ${CADDY_LOCATION:-./caddy}/caddy_data:/data
    restart: always
