name: DigitalOcean Build and Deploy

on:
  push:
    branches:
      - '**'

env:
  IMMICH_TEST_RUN_TIMEOUT: 300 # 5 minutes - timeout for immich test
  IMMICH_TEST_RUN_ENDPOINT: "https://localhost/api/server/ping" # endpoint to test immich during build
  IMMICH_TEST_RUN_SLEEP_TIME: 20 # time between tests
  IMMICH_TEST_PROD_BRANCH: "main"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run DigitalOcean Build and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: Setup `packer`
        uses: hashicorp/setup-packer@ce93c3c08a6c2ff2275bf4b54ff0d9a75f6c9789 # v3.4.0
        id: do_setup
        with:
          version: "1.10.0" # packer version

      - name: Run `packer init`
        id: do_init
        run: "packer init ./digital-ocean/init.pkr.hcl"

      - name: Build digitalocean snapshot
        id: do_build
        working-directory: ./digital-ocean
        run: "packer build template.json"
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          GITHUB_IMMICH_BRANCH: ${{ github.ref_name }}
